### ISSUE TITLE
Can't get the latest v1.8.1 to work with Forms and Prism

### ISSUE THREAD

**Issue by MagnusJohansson** [baskren/Forms9Patch#28] opened 2019-09-22 16:45 UTC
I have a a Forms project that uses Prism and the DryIoc container.

Had no issues with v1.8.0.5, but with v1.8.1 I get this runtime error.
Any ideas what could cause this?

> **DryIoc.ContainerException:** 'Implementation type is not specified when using automatic constructor selection: Object {DryIoc.IfUnresolved.ReturnDefault} as parameter "obj" FactoryId=71 with passed arguments [md5a0b09796d6decdcfd2b50232e8e349e8.MainActivity@d4a529e]
>   in Forms9Patch.Droid.LabelRenderer {DryIoc.IfUnresolved.ReturnDefault} FactoryId=70 with passed arguments [md5a0b09796d6decdcfd2b50232e8e349e8.MainActivity@d4a529e] IsResolutionCall
>   from Container without Scope
>  with Rules with {AutoConcreteTypeResolution} and without {UseFastExpressionCompilerIfPlatformSupported}
>  with Made={FactoryMethod=ConstructorWithResolvableArguments}'
> 
> 09-22 18:10:10.839 E/mono-rt ( 7312): [ERROR] FATAL UNHANDLED EXCEPTION: DryIoc.ContainerException: Implementation type is not specified when using automatic constructor selection: Object {DryIoc.IfUnresolved.ReturnDefault} as parameter "obj" FactoryId=71 with passed arguments [md5a0b09796d6decdcfd2b50232e8e349e8.MainActivity@d4a529e]
**> 09-22 18:10:10.839 E/mono-rt ( 7312):   in Forms9Patch.Droid.LabelRenderer {DryIoc.IfUnresolved.ReturnDefault} FactoryId=70 with passed arguments [md5a0b09796d6decdcfd2b50232e8e349e8.MainActivity@d4a529e] IsResolutionCall**
> 09-22 18:10:10.839 E/mono-rt ( 7312):   from Container without Scope
> 09-22 18:10:10.839 E/mono-rt ( 7312):  with Rules with {AutoConcreteTypeResolution} and without {UseFastExpressionCompilerIfPlatformSupported}
> 09-22 18:10:10.839 E/mono-rt ( 7312):  with Made={FactoryMethod=ConstructorWithResolvableArguments}
> 09-22 18:10:10.839 E/mono-rt ( 7312):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.74(intptr,intptr,intptr,intptr,intptr)
> 09-22 18:10:10.839 E/mono-rt ( 7312):   at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.74(intptr,intptr,intptr,intptr,intptr)
> 09-22 18:10:10.843 D/        ( 7312): HostConnection::get() New Host Connection established 0xbdaae500, tid 7312

**Comment by baskren** [comment] 2019-09-26 00:27
@MagnusJohansson -

Maybe ... I did add an additional constructor to Form9Patch.Droid.LabelRenderer in order to address issue #25.  That being said, there is no way for me to know (or address the root cause) without being able to replicate the issue.  Can you share with me a sample project that demonstrates this issue?

**Comment by baskren** [comment] 2019-11-02 12:42
@MagnusJohansson - I will be closing this next week unless you can share with me sample project.

**Comment by baskren** [comment] 2019-11-26 11:06
Closing.

**Closed by baskren** 2019-11-26 11:06 UTC
