### ISSUE TITLE
OnActionTagTapped not firering

### ISSUE THREAD

**Issue by ITR13** [baskren/Forms9Patch#57] opened 2020-05-22 10:38 UTC
Minimal Reproduction: [https://github.com/ITR13/Forms9Patch-OnActionTagTapped](https://github.com/ITR13/Forms9Patch-OnActionTagTapped)
Visual Studio -> Create New Project -> Blank Project
Added `Forms9Patch.Droid.Settings.Initialize(this)` in Android's MainActivity.cs
Modified MainPage.xaml and MainPage.xaml.cs

Running this shows "Click here!" as an URL in the upper left courner, but clicking it does nothing.
Putting a breakpoint in URLTagged doesn't stop execution, nor is the exception in it thrown.

Phone: Google Pixel running Android 10

**Comment by baskren** [comment] 2020-06-24 14:33
looking into this now.  It appears to be almost working ... but only after trying several times.

**Comment by baskren** [comment] 2020-06-24 14:54
ok, found the fix but don't understand the root cause.  

FormsGestures.Droid.PointExtensions.ToNativePoint(this Point p) used to be

```
        public static Android.Graphics.Point ToNativePoint(this Point p)
        {
            return new Android.Graphics.Point((int)(p.X * Density), (int)(p.Y * Density));
        }
```

where `public static readonly float Density = Droid.Settings.Context.Resources.DisplayMetrics.Density;`

And that has been around since 4/24/2019 (and was tested at that time to assure its working).  Something has changed in that the `Density` multiplication is not needed anymore.  Now, the following appears to work perfectly well:

```
public static Android.Graphics.Point ToNativePoint(this Point p)
            => new Android.Graphics.Point((int)p.X, (int)p.Y);
```

This will be in the next update.

**Comment by baskren** [comment] 2020-06-29 23:21
Version 2.3 has been released.  Please let me know if this does not fix this issue.

**Closed by baskren** 2020-06-29 23:21 UTC
Labels: bug
